external_entities.external_entity_type.*:
  type: config_entity
  label: 'External entity type'
  mapping:
    id:
      type: string
      label: 'Id'
    label:
      type: label
      label: 'Name'
    label_plural:
      type: label
      label: 'Plural name'
    description:
      type: text
      label: 'Description'
    read_only:
      type: boolean
      label: 'Read only'
    generate_aliases:
      type: boolean
      label: 'Automatically generate aliases'
    field_mapper_id:
      type: string
      label: 'Field mapper plugin ID'
    field_mapper_config:
      type: plugin.plugin_configuration.external_entities_field_mapper.[%parent.field_mapper_id]
    storage_client_id:
      type: string
      label: 'Storage client plugin ID'
    storage_client_config:
      type: plugin.plugin_configuration.external_entities_storage_client.[%parent.storage_client_id]
    persistent_cache_max_age:
      type: integer
      label: 'Persistent cache maximum age'
    annotation_entity_type_id:
      type: string
      label: 'Annotation entity type id'
    annotation_bundle_id:
      type: string
      label: 'Annotation bundle id'
    annotation_field_name:
      type: string
      label: 'Annotation field name'
    inherits_annotation_fields:
      type: boolean
      label: 'Inherits annotation fields'

plugin.plugin_configuration.external_entities_field_mapper.*:
  type: mapping

plugin.plugin_configuration.external_entities_storage_client.*:
  type: mapping
